### ISSUE TITLE
Suggested change to Boo III velocity dispersion

### ISSUE THREAD

**Issue by willcerny** [apace7/local_volume_database#4]
Carlin and Sand (2018) update the velocity dispersion of Boo III from 14.0 --> 10.7.

See here: https://arxiv.org/abs/1805.11624

**Comment by apace7** [comment]
Updated in this commit https://github.com/apace7/local_volume_database/commit/b6388e6d4821334b409170599264dfce52015e44#diff-87c14deba6ce87c5bad5512d2ea18aea5d1f003f8124ca03410c9fdac8735e58
